---
title: "10_pretreatment"
author: "PabloVigneron"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output: 
  bookdown::html_document2:
   fig_caption: yes
   tab_caption: yes
   number_sections: yes
   global_numbering: yes
   toc: yes
   toc_float:
         toc_collapsed: yes
         toc_depth: 2
   code_folding: hide
   css: "style.css"
#bibliography: .bib
#link-citations: true
#cls: apa.cls
#editor_options: 
#  markdown: 
#    wrap: sentence
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```


```{r}
#Importation des packages
library(tidyverse)
library(janitor)
library(sf)
library(mapview)
library(aspe)
library(dplyr)
library(usethis)
```

```{r}
# Importation des données - Informations opération pêche
base_operation <-
  readxl::read_xls(path = '../raw_data/RHP-RCS-RCO-REF DR 9.xls', sheet = "DONNEES SOURCE")
```

```{r}
ope_clean <- base_operation %>% # Ctrl+shift+M
  janitor::clean_names() %>%
  mutate(
    protocole = as.factor(protocole),
    reseaux = case_when(
      rhp_old == 1 ~ "rhp_old",
      rhp_new == 1 ~ "rhp_new",
      old_ref == 1 ~ "old_ref",
      rrp == 1 ~ "rrp",
      rcs == 1 ~ "rcs"
    )
  ) 
```

```{r}
summary(ope_clean$protocole)
```

# importation tableau espèces TAXREF

```{r}
taxref <- 
  read_table('../raw_data/TAXREFv18.txt')
  
```

```{r}
summary(taxref)
```

# Représentation cartographique du secteur d'étude et des stations correspondantes

```{r, fig.cap=" Localisation des secteurs et sites d’études.",fig.width = 7, fig.height = 5}
# Représentation cartographique du secteur d'étude et des stations correspondants

sites_geo <- ope_clean %>%
  filter(!is.na(xaval_l93) & !is.na(yaval_l93)) %>%
  dplyr::select(
    code_station_bhp,
    xaval_l93,
    yaval_l93,
    nom_sandre,
    protocole,
    mode_prospection,
    annee_peche, 
    reseaux
  ) %>%
  st_as_sf(coords = c("xaval_l93", "yaval_l93"), crs = 2154)


mapview(
  sites_geo,
  zcol = "protocole",
  col.regions = c("darkseagreen3" , "indianred1",  "purple")
)

```


# Installer le package aspe
```{r}
#devtools::install_github("pascalirz/aspe")
```

Pour des raisons de problème de proxy, le package "aspe" a été téléchargé manuellement à partir d'un document ".tar". 
```{r}
#install.packages("C:/Users/pablo.vigneron/Downloads/PascalIrz-aspe-v0.5.2-6-gec29cc2(2).tar.gz", repos = NULL, type = "source")
```

#Stocker les informations de connexion dans son R environnement 
```{r}
## 1° - ouvrir le fichier de configuration de l'environnement R avec la fonction du package usethis (installer le package si nécessaire).
usethis::edit_r_environ()

```

#Importation de la base depuis l'IDG

```{r}
# connexion à l'IDG
# ! veillez à disposer des informations de connexion et un droit d'accès
aspe_db <- imp_connecter_aspe_idg()

# importation des tables de la base aspe
imp_importer_aspe_idg(aspe_db)
```

```{r}
export_tables_rdata('../processed-data')
```

